### ISSUE TITLE
Is there a script to produce the captions  and  region   like Figure 4 in the paper

### ISSUE THREAD

**Issue by nyj-ocean** [Dong-JinKim/DenseRelationalCaptioning#5]
Thanks for your great work!

I want to know if there is a script to produce the captions  and  region  like Figure 4 in the paper?

![tttt](https://user-images.githubusercontent.com/55009815/87307656-966af600-c54c-11ea-8e2a-5049c9300f48.png)

**Comment by Dong-JinKim** [comment]
I manually drew Fig.4 by manually collecting the output captions. The script to draw captions and regions is currently in progress. I will let you know as soon as the script is ready.

**Comment by nyj-ocean** [comment]
@Dong-JinKim 
Thanks a lot .
I was interested in your great work.
I wait for your good news !
